spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://i6a606.p.ssafy.io:3306/glanner
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: glanner.ssafy@gmail.com
    password: glanner123!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

glanner:
  max-perssonel-size: 5

jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

sms:
  serviceid: ncp:sms:kr:279856777501:glanner
  accesskey: vqCrek0X5afBgKemOtdP
  secretkey: oJBNw9bRz0aSQ1ZAERXwRckGVF3McVHQc9q79ICE